#!/usr/bin/env node
/* Bundles engine/src/*.js into site/engine/legend-engine.js.
 *
 * The sources are plain scripts, not ES modules: the build concatenates them
 * inside one IIFE so they share a lexical scope. That keeps the engine a
 * single <script> tag with no import map, no bundler config, and no CORS
 * story — which is the whole point, since every Legend game is one
 * self-contained HTML file.
 *
 * Usage:  node engine/build.js [--watch]
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(__dirname, 'src');
const OUT = path.join(ROOT, 'site', 'engine', 'legend-engine.js');
const VERSION = require('./version.json').version;

function build() {
  const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
  if (!files.length) throw new Error('no sources found in engine/src');

  const parts = files.map((f) => {
    const body = fs.readFileSync(path.join(SRC, f), 'utf8');
    // ES module syntax would break the concatenation, so fail loudly rather
    // than emitting a bundle that dies at parse time in the browser.
    if (/^\s*(import|export)\s/m.test(body)) {
      throw new Error(`${f} uses import/export — engine sources must be plain scripts`);
    }
    return `\n/* ─────────── ${f} ─────────── */\n${body}`;
  });

  const banner = `/*!
 * Legend Engine v${VERSION}
 * Real-time physics, destruction, fluids and PBR rendering for the browser.
 * Built for Legend — https://github.com/dax-code-bro/untitled-new-game-project
 * Generated by engine/build.js — edit engine/src/*.js, not this file.
 */`;

  const bundle = `${banner}
(function (global) {
'use strict';
${parts.join('\n')}

/* ─────────── public surface ─────────── */
const LegendEngine = {
  version: '${VERSION}',
  // top-level API
  create: createEngine,
  quickStart,
  // building blocks, for games that want the lower level
  Vec3, Quat, Mat3, Mat4, Aabb, Rng, Noise,
  Geometry, Shapes, convexHull, hullToGeometry,
  Engine, Actor, Material, Body, PhysicsWorld,
  Fluid, Fracture, ParticleSystem, Skeleton, AnimationClip, Face, Bone, makeHumanoidSkeleton, makeHumanoidMesh, solveSkinWeights, smoothNormals, parseRiggedMesh, skeletonFromRig,
  makePistol1911, makeViewmodelArms, GRIP_KINDS, makeZombieClips, buildZombieBodyGeometry, buildZombieClothGeometry, zombieWoundSpots,
  Grass, Input, Audio,
  clamp, lerp, smoothstep,
};

global.LegendEngine = LegendEngine;
global.LE = global.LE || LegendEngine;
if (typeof module !== 'undefined' && module.exports) module.exports = LegendEngine;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, bundle);

  // Parse-check the result. `new Function` compiles without executing, so a
  // syntax error surfaces here instead of in the browser console.
  try {
    // eslint-disable-next-line no-new-func
    new Function(bundle);
  } catch (err) {
    throw new Error(`bundle has a syntax error: ${err.message}`);
  }

  const kb = (Buffer.byteLength(bundle) / 1024).toFixed(1);
  console.log(`legend-engine.js  ${kb} KB  from ${files.length} modules  (v${VERSION})`);
  return bundle;
}

if (process.argv.includes('--watch')) {
  build();
  fs.watch(SRC, () => {
    try { build(); } catch (e) { console.error(e.message); }
  });
  console.log('watching engine/src …');
} else {
  build();
}
