#!/usr/bin/env node
/* Bundles engine/src/*.js into site/engine/legend-engine.js.
 *
 * The sources are plain scripts, not ES modules: the build concatenates them
 * inside one IIFE so they share a lexical scope. That keeps the engine a
 * single <script> tag with no import map, no bundler config, and no CORS
 * story — which is the whole point, since every Legend game is one
 * self-contained HTML file.
 *
 * Usage:  node engine/build.js [--watch] [--out <path>]
 *
 * --out writes somewhere other than site/engine/legend-engine.js. That
 * exists so a bundle can be built and measured WHILE the test suite is
 * running against the real one -- the suite reads the file at run time,
 * so rebuilding underneath it silently changes what half the run was
 * testing.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(__dirname, 'src');
const outAt = process.argv.indexOf('--out');
const OUT = outAt >= 0 && process.argv[outAt + 1]
  ? path.resolve(process.argv[outAt + 1])
  : path.join(ROOT, 'site', 'engine', 'legend-engine.js');
const VERSION = require('./version.json').version;

function build() {
  const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
  if (!files.length) throw new Error('no sources found in engine/src');

  const parts = files.map((f) => {
    const body = fs.readFileSync(path.join(SRC, f), 'utf8');
    // ES module syntax would break the concatenation, so fail loudly rather
    // than emitting a bundle that dies at parse time in the browser.
    if (/^\s*(import|export)\s/m.test(body)) {
      throw new Error(`${f} uses import/export — engine sources must be plain scripts`);
    }
    return `\n/* ─────────── ${f} ─────────── */\n${body}`;
  });

  const banner = `/*!
 * Legend Engine v${VERSION}
 * Real-time physics, destruction, fluids and PBR rendering for the browser.
 * Built for Legend — https://github.com/dax-code-bro/untitled-new-game-project
 * Generated by engine/build.js — edit engine/src/*.js, not this file.
 */`;

  const bundle = `${banner}
(function (global) {
'use strict';
${parts.join('\n')}

/* ─────────── public surface ─────────── */
const LegendEngine = {
  version: '${VERSION}',
  // top-level API
  create: createEngine,
  quickStart,
  // building blocks, for games that want the lower level
  Vec3, Quat, Mat3, Mat4, Aabb, Rng, Noise,
  Geometry, Shapes, convexHull, hullToGeometry,
  Engine, Actor, Material, Body, PhysicsWorld,
  Fluid, Fracture, ParticleSystem, Skeleton, AnimationClip, Face, Bone, makeHumanoidSkeleton, makeHumanoidMesh, solveSkinWeights, smoothNormals, parseRiggedMesh, skeletonFromRig,
  makePistol1911, makeViewmodelArms, GRIP_KINDS, makeHumanoidClips, makeZombieClips, buildClip, Animator, gaitRate, buildZombieBodyGeometry, buildZombieClothGeometry, zombieWoundSpots,
  Grass, Input, Audio,
  /* The procedural texture bank, exported so it can be MEASURED.

     Every surface recipe multiplies the colour its material asks for, and
     three separate "the lighting is wrong" investigations turned out to be
     a recipe averaging a third of mid-grey. None of them could be settled
     from outside the bundle, because the bank was a module-level const
     nobody could reach. engine/test/texture.test.js reaches it now. */
  Textures: TextureLib,
  /* The weapon tables and their builders, exported for the same reason
     the texture bank is: so they can be MEASURED without a browser.

     Sixty guns were compared side by side by rendering all sixty and
     diffing the pictures, which needs a GPU, takes minutes, and can
     only answer questions about what a camera happens to see. These
     builders are pure geometry -- no GL, no canvas -- so a Node test
     can ask how many vertices a part has, where its bounding box is,
     and whether two weapons differ by anything at all. The pistol
     cluster that started this was found with a renderer and confirmed
     in forty milliseconds with arithmetic. */
  SERVICE_KINDS, makeServiceArm,
  /* And the twelve that are hand-dimensioned rather than table-built,
     for the same reason. See BESPOKE_ARMS in 97a-arms.js. */
  BESPOKE_ARMS, makeBespokeArm,
  WEAPON_ACTIONS, weaponAction, poseAction,
  /* The shared motion vocabulary -- easing with anticipation and
     overshoot, analytic settle/kick curves, mechanism strokes, arcs,
     exact springs, smooth noise. See 90a-motion.js. */
  Motion, Ease, Spring,
  /* The reload, as a thing you can watch. Both games drive the same
     six load paths from here -- see 97f-reload.js. */
  RELOAD_WINDOW, RELOAD_CARRIES, RELOAD_HOLD, RELOAD_AMMO,
  reloadFetch, reloadOnscreen, reloadReach, stowReloadProp,
  /* The inspect, shared for the same reason -- see 97g-inspect.js. */
  INSPECT_TIME, INSPECT_CANCEL, inspectPose,
  /* Brass and spent magazines -- see 97h-spent.js. */
  keepSpent,
  /* The noises a weapon makes when nobody is shooting it. */
  HANDLING, RELOAD_SOUNDS, INSPECT_SOUNDS,
  bakeCavityAO,
  clamp, lerp, smoothstep,
};

global.LegendEngine = LegendEngine;
global.LE = global.LE || LegendEngine;
if (typeof module !== 'undefined' && module.exports) module.exports = LegendEngine;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, bundle);

  // Parse-check the result. `new Function` compiles without executing, so a
  // syntax error surfaces here instead of in the browser console.
  try {
    // eslint-disable-next-line no-new-func
    new Function(bundle);
  } catch (err) {
    throw new Error(`bundle has a syntax error: ${err.message}`);
  }

  const kb = (Buffer.byteLength(bundle) / 1024).toFixed(1);
  console.log(`legend-engine.js  ${kb} KB  from ${files.length} modules  (v${VERSION})`);
  return bundle;
}

if (process.argv.includes('--watch')) {
  build();
  fs.watch(SRC, () => {
    try { build(); } catch (e) { console.error(e.message); }
  });
  console.log('watching engine/src …');
} else {
  build();
}
