#!/usr/bin/env node
/* Bundles survivor/src/*.js into site/survivor/survivor.js.
 *
 * Same approach as the engine build, and for the same reason: the sources
 * are plain scripts concatenated inside one IIFE so they share a lexical
 * scope, which keeps the whole game two <script> tags with no bundler, no
 * import map and no CORS story.
 *
 * Usage:  node survivor/build.js [--watch]
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(__dirname, 'src');
const OUT = path.join(ROOT, 'site', 'survivor', 'survivor.js');
const VERSION = require('./version.json').version;

/* Everything the game exposes. Kept explicit rather than generated, so that
   adding something to the public surface is a decision rather than an
   accident of where a `const` happened to be written. */
const EXPORTS = [
  'UNIT', 'clamp01', 'clampTo', 'lerpN', 'ramp', 'speedOfSound', 'airDensity',
  'grainsToKg', 'fpsToMs', 'msToFps', 'yardsToM', 'joulesToFtLb', 'ftLbToJoules',
  'cToF', 'fToC',

  'Physiology', 'pandolfWatts', 'basalMetabolicRate', 'bodySurfaceArea', 'windChill',
  'TERRAIN_FACTOR', 'DEHYDRATION', 'CORE_TEMP',

  'DiseaseSystem', 'Infection', 'PATHOGENS', 'PATHOGEN_BY_ID', 'SYMPTOM', 'TREATMENT', 'VECTOR',

  'InjurySystem', 'Wound', 'BODY_REGION', 'BONE', 'WOUND_TYPE', 'CARE',

  'Projectile', 'integrateTrajectory', 'zeroAngleDeg', 'freeRecoil', 'muzzleRise',
  'CARTRIDGES', 'DRAG_G1', 'DRAG_G7', 'dragCoefficient',

  'penetrate', 'penetrationDepth', 'layer', 'ASSEMBLY', 'PEN_MATERIAL',
  'woundSeverity', 'bulletDynamics', 'CORE_STRENGTH',

  'SPECIES', 'SPECIES_LIST', 'DIET', 'ACTIVITY', 'rollIndividual', 'butcherYield',
  'Ecology', 'Animal', 'Carcass', 'FeedingZone', 'BEHAVIOUR',

  'Fishery', 'Fish', 'WaterBody', 'FISH_SPECIES', 'FISH_SPECIES_LIST',

  'WorldClock', 'Weather', 'SEASON', 'solarPosition', 'solarDeclination', 'daylightHours',

  'generateIsland', 'Heightmap', 'ValueNoise', 'hydraulicErosion', 'thermalErosion',
  'fillDepressions', 'classifyTerrain', 'classifyBiome', 'traceRivers', 'BIOME',
  'ISLAND_DEFAULTS',

  'Building', 'Room', 'Wall', 'generateHouse', 'generateFloorPlan', 'buildWalls',
  'wireBuilding', 'ROOM', 'ROOM_LOOT',

  'POI_KIND', 'POI_SPECS', 'siteAll', 'buildPoi',

  'ElectricalSystem', 'Circuit', 'Conductor', 'Load', 'PowerSource', 'checkWiring',
  'AWG', 'BODY_RESISTANCE', 'SHOCK_THRESHOLDS',

  'Firearm', 'WEAPONS', 'ATTACHMENT', 'ACTION', 'PART', 'POWDER', 'handload',
  'salvageComponents',

  'Fire', 'Provision', 'FIRE_KIND', 'FOOD_STATE', 'SAFE_CORE',
  'WATER_TREATMENT', 'treatWater', 'drinkTreated',

  'Horse', 'Vehicle', 'GAIT', 'HORSE_BREED', 'VEHICLE_SPEC', 'fuelViability',

  'World', 'Player', 'Inventory', 'GAME_MODE',
];

function build() {
  const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
  if (!files.length) throw new Error('no sources found in survivor/src');

  const parts = files.map((f) => {
    const body = fs.readFileSync(path.join(SRC, f), 'utf8');
    if (/^\s*(import|export)\s/m.test(body)) {
      throw new Error(`${f} uses import/export — survivor sources must be plain scripts`);
    }
    return `\n/* ─────────── ${f} ─────────── */\n${body}`;
  });

  const banner = `/*!
 * Survivor v${VERSION}
 * The simulation layer: physiology, disease, ballistics, ecology, terrain.
 * Runs on the Legend Engine — https://github.com/dax-code-bro/untitled-new-game-project
 * Generated by survivor/build.js — edit survivor/src/*.js, not this file.
 */`;

  const bundle = `${banner}
(function (global) {
'use strict';
${parts.join('\n')}

/* ─────────── public surface ─────────── */
const Survivor = {
  version: '${VERSION}',
${EXPORTS.map((e) => `  ${e},`).join('\n')}
};

global.Survivor = Survivor;
global.SV = global.SV || Survivor;
if (typeof module !== 'undefined' && module.exports) module.exports = Survivor;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, bundle);

  // Compile without executing, so a syntax error or a missing export surfaces
  // here rather than in the browser console.
  try {
    // eslint-disable-next-line no-new-func
    new Function(bundle);
  } catch (err) {
    throw new Error(`bundle has a syntax error: ${err.message}`);
  }

  const kb = (Buffer.byteLength(bundle) / 1024).toFixed(1);
  console.log(`survivor.js  ${kb} KB  from ${files.length} modules  (v${VERSION})`);
  return bundle;
}

if (process.argv.includes('--watch')) {
  build();
  fs.watch(SRC, () => { try { build(); } catch (e) { console.error(e.message); } });
  console.log('watching survivor/src …');
} else {
  build();
}
