# Writes OUT (a .cpp) that holds each input file as a byte array:
#   cmake -DOUT=<file.cpp> -DNAME1=a -DFILE1=<path> [-DNAME2=b -DFILE2=<path> ...] -P EmbedFiles.cmake
# For each name: extern const unsigned char <name>[]; extern const unsigned int <name>Size;
set(code "// Generated by cmake/EmbedFiles.cmake - do not edit.\n")
foreach(i RANGE 1 9)
  if(NOT DEFINED NAME${i})
    break()
  endif()
  file(READ "${FILE${i}}" hex HEX)
  string(LENGTH "${hex}" hexLen)
  math(EXPR size "${hexLen} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(APPEND code "extern const unsigned char ${NAME${i}}[] = {${bytes}};\nextern const unsigned int ${NAME${i}}Size = ${size};\n")
endforeach()
file(WRITE "${OUT}" "${code}")
