const fs=require('fs'),path=require('path'),http=require('http'),url=require('url');
const {chromium}=require('playwright');
const SITE=path.join('/home/user/Untitled-new-game-project','site');
const OUT='/tmp/claude-0/elimshots';
const MIME={'.html':'text/html','.js':'text/javascript'};
const server=http.createServer((q,r)=>{let p=path.join(SITE,decodeURIComponent(url.parse(q.url).pathname));
 if(p.endsWith('/'))p+='index.html';fs.readFile(p,(e,b)=>{if(e){r.writeHead(404);return r.end('x');}
 r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});r.end(b);});});
(async()=>{fs.mkdirSync(OUT,{recursive:true});await new Promise(r=>server.listen(8125,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--disable-dev-shm-usage']});
const pg=await b.newPage({viewport:{width:1100,height:700}});
pg.on('pageerror',e=>console.log('ERR',e.message));
await pg.goto('http://localhost:8125/survivor/index.html',{waitUntil:'load'});
await pg.waitForSelector('#startBtn:not([hidden])',{timeout:300000});
await pg.click('#startBtn');await pg.waitForTimeout(2500);
await pg.evaluate(()=>{const S=window.SURVIVOR;S.world.clock.simSeconds=12*3600;
 document.querySelector('#hud').hidden=true;document.querySelector('#help').hidden=true;
 const t=document.querySelector('#tutorial');if(t)t.hidden=true;
 document.querySelector('#vignette').style.display='none';document.querySelector('#damage').style.display='none';});
const look=()=>pg.evaluate(()=>{const S=window.SURVIVOR;const p=S.game.camera.position;
 S.game.camera.target.set(p.x+0.05,p.y-1.3,p.z+0.75);S.game._camMode='manual';});
const kill=(pred)=>pg.evaluate((src)=>{const S=window.SURVIVOR;const f=new Function('n','return '+src);
 for(const a of S.game.actors.slice()){if(/^fp:/.test(a.name||'')&&f(a.name))a.destroy();}},pred);
await look();await pg.waitForTimeout(800);await pg.screenshot({path:path.join(OUT,'0-all.png')});
await kill('/sleeveU$/.test(n)');await look();await pg.waitForTimeout(700);await pg.screenshot({path:path.join(OUT,'1-no-upper-sleeve.png')});
await kill('/:shoulder$/.test(n)');await look();await pg.waitForTimeout(700);await pg.screenshot({path:path.join(OUT,'2-no-shoulder.png')});
await kill('/:upperArm$/.test(n)');await look();await pg.waitForTimeout(700);await pg.screenshot({path:path.join(OUT,'3-no-upperarm.png')});
await kill('/trouser|:thigh$|:knee$/.test(n)');await look();await pg.waitForTimeout(700);await pg.screenshot({path:path.join(OUT,'4-no-thigh.png')});
console.log('ok');await b.close();server.close();})();
