#include "core/GL.h"
#include <cstdio>

PFN_psglClear psgl_Clear = nullptr;
PFN_psglClearColor psgl_ClearColor = nullptr;
PFN_psglClearDepth psgl_ClearDepth = nullptr;
PFN_psglViewport psgl_Viewport = nullptr;
PFN_psglEnable psgl_Enable = nullptr;
PFN_psglDisable psgl_Disable = nullptr;
PFN_psglCullFace psgl_CullFace = nullptr;
PFN_psglBlendFunc psgl_BlendFunc = nullptr;
PFN_psglDepthFunc psgl_DepthFunc = nullptr;
PFN_psglDepthMask psgl_DepthMask = nullptr;
PFN_psglColorMask psgl_ColorMask = nullptr;
PFN_psglPolygonOffset psgl_PolygonOffset = nullptr;
PFN_psglGenBuffers psgl_GenBuffers = nullptr;
PFN_psglBindBuffer psgl_BindBuffer = nullptr;
PFN_psglBufferData psgl_BufferData = nullptr;
PFN_psglBufferSubData psgl_BufferSubData = nullptr;
PFN_psglDeleteBuffers psgl_DeleteBuffers = nullptr;
PFN_psglGenVertexArrays psgl_GenVertexArrays = nullptr;
PFN_psglBindVertexArray psgl_BindVertexArray = nullptr;
PFN_psglDeleteVertexArrays psgl_DeleteVertexArrays = nullptr;
PFN_psglEnableVertexAttribArray psgl_EnableVertexAttribArray = nullptr;
PFN_psglVertexAttribPointer psgl_VertexAttribPointer = nullptr;
PFN_psglVertexAttribDivisor psgl_VertexAttribDivisor = nullptr;
PFN_psglDrawArrays psgl_DrawArrays = nullptr;
PFN_psglDrawElements psgl_DrawElements = nullptr;
PFN_psglDrawElementsInstanced psgl_DrawElementsInstanced = nullptr;
PFN_psglCreateShader psgl_CreateShader = nullptr;
PFN_psglShaderSource psgl_ShaderSource = nullptr;
PFN_psglCompileShader psgl_CompileShader = nullptr;
PFN_psglGetShaderiv psgl_GetShaderiv = nullptr;
PFN_psglGetShaderInfoLog psgl_GetShaderInfoLog = nullptr;
PFN_psglCreateProgram psgl_CreateProgram = nullptr;
PFN_psglAttachShader psgl_AttachShader = nullptr;
PFN_psglLinkProgram psgl_LinkProgram = nullptr;
PFN_psglGetProgramiv psgl_GetProgramiv = nullptr;
PFN_psglGetProgramInfoLog psgl_GetProgramInfoLog = nullptr;
PFN_psglDeleteShader psgl_DeleteShader = nullptr;
PFN_psglDeleteProgram psgl_DeleteProgram = nullptr;
PFN_psglUseProgram psgl_UseProgram = nullptr;
PFN_psglGetUniformLocation psgl_GetUniformLocation = nullptr;
PFN_psglUniform1i psgl_Uniform1i = nullptr;
PFN_psglUniform1f psgl_Uniform1f = nullptr;
PFN_psglUniform2f psgl_Uniform2f = nullptr;
PFN_psglUniform3f psgl_Uniform3f = nullptr;
PFN_psglUniform4f psgl_Uniform4f = nullptr;
PFN_psglUniform3fv psgl_Uniform3fv = nullptr;
PFN_psglUniform4fv psgl_Uniform4fv = nullptr;
PFN_psglUniformMatrix4fv psgl_UniformMatrix4fv = nullptr;
PFN_psglGenTextures psgl_GenTextures = nullptr;
PFN_psglBindTexture psgl_BindTexture = nullptr;
PFN_psglTexImage2D psgl_TexImage2D = nullptr;
PFN_psglTexParameteri psgl_TexParameteri = nullptr;
PFN_psglTexParameterfv psgl_TexParameterfv = nullptr;
PFN_psglActiveTexture psgl_ActiveTexture = nullptr;
PFN_psglGenerateMipmap psgl_GenerateMipmap = nullptr;
PFN_psglDeleteTextures psgl_DeleteTextures = nullptr;
PFN_psglGenFramebuffers psgl_GenFramebuffers = nullptr;
PFN_psglBindFramebuffer psgl_BindFramebuffer = nullptr;
PFN_psglFramebufferTexture2D psgl_FramebufferTexture2D = nullptr;
PFN_psglCheckFramebufferStatus psgl_CheckFramebufferStatus = nullptr;
PFN_psglDeleteFramebuffers psgl_DeleteFramebuffers = nullptr;
PFN_psglDrawBuffer psgl_DrawBuffer = nullptr;
PFN_psglReadBuffer psgl_ReadBuffer = nullptr;
PFN_psglReadPixels psgl_ReadPixels = nullptr;
PFN_psglPixelStorei psgl_PixelStorei = nullptr;
PFN_psglGetString psgl_GetString = nullptr;
PFN_psglGetError psgl_GetError = nullptr;

namespace ps {
bool loadGL(GLLoadFn getProc) {
    bool ok = true;
    psgl_Clear = reinterpret_cast<PFN_psglClear>(getProc("glClear"));
    if (!psgl_Clear) { std::fprintf(stderr, "Missing GL function glClear\n"); ok = false; }
    psgl_ClearColor = reinterpret_cast<PFN_psglClearColor>(getProc("glClearColor"));
    if (!psgl_ClearColor) { std::fprintf(stderr, "Missing GL function glClearColor\n"); ok = false; }
    psgl_ClearDepth = reinterpret_cast<PFN_psglClearDepth>(getProc("glClearDepth"));
    if (!psgl_ClearDepth) { std::fprintf(stderr, "Missing GL function glClearDepth\n"); ok = false; }
    psgl_Viewport = reinterpret_cast<PFN_psglViewport>(getProc("glViewport"));
    if (!psgl_Viewport) { std::fprintf(stderr, "Missing GL function glViewport\n"); ok = false; }
    psgl_Enable = reinterpret_cast<PFN_psglEnable>(getProc("glEnable"));
    if (!psgl_Enable) { std::fprintf(stderr, "Missing GL function glEnable\n"); ok = false; }
    psgl_Disable = reinterpret_cast<PFN_psglDisable>(getProc("glDisable"));
    if (!psgl_Disable) { std::fprintf(stderr, "Missing GL function glDisable\n"); ok = false; }
    psgl_CullFace = reinterpret_cast<PFN_psglCullFace>(getProc("glCullFace"));
    if (!psgl_CullFace) { std::fprintf(stderr, "Missing GL function glCullFace\n"); ok = false; }
    psgl_BlendFunc = reinterpret_cast<PFN_psglBlendFunc>(getProc("glBlendFunc"));
    if (!psgl_BlendFunc) { std::fprintf(stderr, "Missing GL function glBlendFunc\n"); ok = false; }
    psgl_DepthFunc = reinterpret_cast<PFN_psglDepthFunc>(getProc("glDepthFunc"));
    if (!psgl_DepthFunc) { std::fprintf(stderr, "Missing GL function glDepthFunc\n"); ok = false; }
    psgl_DepthMask = reinterpret_cast<PFN_psglDepthMask>(getProc("glDepthMask"));
    if (!psgl_DepthMask) { std::fprintf(stderr, "Missing GL function glDepthMask\n"); ok = false; }
    psgl_ColorMask = reinterpret_cast<PFN_psglColorMask>(getProc("glColorMask"));
    if (!psgl_ColorMask) { std::fprintf(stderr, "Missing GL function glColorMask\n"); ok = false; }
    psgl_PolygonOffset = reinterpret_cast<PFN_psglPolygonOffset>(getProc("glPolygonOffset"));
    if (!psgl_PolygonOffset) { std::fprintf(stderr, "Missing GL function glPolygonOffset\n"); ok = false; }
    psgl_GenBuffers = reinterpret_cast<PFN_psglGenBuffers>(getProc("glGenBuffers"));
    if (!psgl_GenBuffers) { std::fprintf(stderr, "Missing GL function glGenBuffers\n"); ok = false; }
    psgl_BindBuffer = reinterpret_cast<PFN_psglBindBuffer>(getProc("glBindBuffer"));
    if (!psgl_BindBuffer) { std::fprintf(stderr, "Missing GL function glBindBuffer\n"); ok = false; }
    psgl_BufferData = reinterpret_cast<PFN_psglBufferData>(getProc("glBufferData"));
    if (!psgl_BufferData) { std::fprintf(stderr, "Missing GL function glBufferData\n"); ok = false; }
    psgl_BufferSubData = reinterpret_cast<PFN_psglBufferSubData>(getProc("glBufferSubData"));
    if (!psgl_BufferSubData) { std::fprintf(stderr, "Missing GL function glBufferSubData\n"); ok = false; }
    psgl_DeleteBuffers = reinterpret_cast<PFN_psglDeleteBuffers>(getProc("glDeleteBuffers"));
    if (!psgl_DeleteBuffers) { std::fprintf(stderr, "Missing GL function glDeleteBuffers\n"); ok = false; }
    psgl_GenVertexArrays = reinterpret_cast<PFN_psglGenVertexArrays>(getProc("glGenVertexArrays"));
    if (!psgl_GenVertexArrays) { std::fprintf(stderr, "Missing GL function glGenVertexArrays\n"); ok = false; }
    psgl_BindVertexArray = reinterpret_cast<PFN_psglBindVertexArray>(getProc("glBindVertexArray"));
    if (!psgl_BindVertexArray) { std::fprintf(stderr, "Missing GL function glBindVertexArray\n"); ok = false; }
    psgl_DeleteVertexArrays = reinterpret_cast<PFN_psglDeleteVertexArrays>(getProc("glDeleteVertexArrays"));
    if (!psgl_DeleteVertexArrays) { std::fprintf(stderr, "Missing GL function glDeleteVertexArrays\n"); ok = false; }
    psgl_EnableVertexAttribArray = reinterpret_cast<PFN_psglEnableVertexAttribArray>(getProc("glEnableVertexAttribArray"));
    if (!psgl_EnableVertexAttribArray) { std::fprintf(stderr, "Missing GL function glEnableVertexAttribArray\n"); ok = false; }
    psgl_VertexAttribPointer = reinterpret_cast<PFN_psglVertexAttribPointer>(getProc("glVertexAttribPointer"));
    if (!psgl_VertexAttribPointer) { std::fprintf(stderr, "Missing GL function glVertexAttribPointer\n"); ok = false; }
    psgl_VertexAttribDivisor = reinterpret_cast<PFN_psglVertexAttribDivisor>(getProc("glVertexAttribDivisor"));
    if (!psgl_VertexAttribDivisor) { std::fprintf(stderr, "Missing GL function glVertexAttribDivisor\n"); ok = false; }
    psgl_DrawArrays = reinterpret_cast<PFN_psglDrawArrays>(getProc("glDrawArrays"));
    if (!psgl_DrawArrays) { std::fprintf(stderr, "Missing GL function glDrawArrays\n"); ok = false; }
    psgl_DrawElements = reinterpret_cast<PFN_psglDrawElements>(getProc("glDrawElements"));
    if (!psgl_DrawElements) { std::fprintf(stderr, "Missing GL function glDrawElements\n"); ok = false; }
    psgl_DrawElementsInstanced = reinterpret_cast<PFN_psglDrawElementsInstanced>(getProc("glDrawElementsInstanced"));
    if (!psgl_DrawElementsInstanced) { std::fprintf(stderr, "Missing GL function glDrawElementsInstanced\n"); ok = false; }
    psgl_CreateShader = reinterpret_cast<PFN_psglCreateShader>(getProc("glCreateShader"));
    if (!psgl_CreateShader) { std::fprintf(stderr, "Missing GL function glCreateShader\n"); ok = false; }
    psgl_ShaderSource = reinterpret_cast<PFN_psglShaderSource>(getProc("glShaderSource"));
    if (!psgl_ShaderSource) { std::fprintf(stderr, "Missing GL function glShaderSource\n"); ok = false; }
    psgl_CompileShader = reinterpret_cast<PFN_psglCompileShader>(getProc("glCompileShader"));
    if (!psgl_CompileShader) { std::fprintf(stderr, "Missing GL function glCompileShader\n"); ok = false; }
    psgl_GetShaderiv = reinterpret_cast<PFN_psglGetShaderiv>(getProc("glGetShaderiv"));
    if (!psgl_GetShaderiv) { std::fprintf(stderr, "Missing GL function glGetShaderiv\n"); ok = false; }
    psgl_GetShaderInfoLog = reinterpret_cast<PFN_psglGetShaderInfoLog>(getProc("glGetShaderInfoLog"));
    if (!psgl_GetShaderInfoLog) { std::fprintf(stderr, "Missing GL function glGetShaderInfoLog\n"); ok = false; }
    psgl_CreateProgram = reinterpret_cast<PFN_psglCreateProgram>(getProc("glCreateProgram"));
    if (!psgl_CreateProgram) { std::fprintf(stderr, "Missing GL function glCreateProgram\n"); ok = false; }
    psgl_AttachShader = reinterpret_cast<PFN_psglAttachShader>(getProc("glAttachShader"));
    if (!psgl_AttachShader) { std::fprintf(stderr, "Missing GL function glAttachShader\n"); ok = false; }
    psgl_LinkProgram = reinterpret_cast<PFN_psglLinkProgram>(getProc("glLinkProgram"));
    if (!psgl_LinkProgram) { std::fprintf(stderr, "Missing GL function glLinkProgram\n"); ok = false; }
    psgl_GetProgramiv = reinterpret_cast<PFN_psglGetProgramiv>(getProc("glGetProgramiv"));
    if (!psgl_GetProgramiv) { std::fprintf(stderr, "Missing GL function glGetProgramiv\n"); ok = false; }
    psgl_GetProgramInfoLog = reinterpret_cast<PFN_psglGetProgramInfoLog>(getProc("glGetProgramInfoLog"));
    if (!psgl_GetProgramInfoLog) { std::fprintf(stderr, "Missing GL function glGetProgramInfoLog\n"); ok = false; }
    psgl_DeleteShader = reinterpret_cast<PFN_psglDeleteShader>(getProc("glDeleteShader"));
    if (!psgl_DeleteShader) { std::fprintf(stderr, "Missing GL function glDeleteShader\n"); ok = false; }
    psgl_DeleteProgram = reinterpret_cast<PFN_psglDeleteProgram>(getProc("glDeleteProgram"));
    if (!psgl_DeleteProgram) { std::fprintf(stderr, "Missing GL function glDeleteProgram\n"); ok = false; }
    psgl_UseProgram = reinterpret_cast<PFN_psglUseProgram>(getProc("glUseProgram"));
    if (!psgl_UseProgram) { std::fprintf(stderr, "Missing GL function glUseProgram\n"); ok = false; }
    psgl_GetUniformLocation = reinterpret_cast<PFN_psglGetUniformLocation>(getProc("glGetUniformLocation"));
    if (!psgl_GetUniformLocation) { std::fprintf(stderr, "Missing GL function glGetUniformLocation\n"); ok = false; }
    psgl_Uniform1i = reinterpret_cast<PFN_psglUniform1i>(getProc("glUniform1i"));
    if (!psgl_Uniform1i) { std::fprintf(stderr, "Missing GL function glUniform1i\n"); ok = false; }
    psgl_Uniform1f = reinterpret_cast<PFN_psglUniform1f>(getProc("glUniform1f"));
    if (!psgl_Uniform1f) { std::fprintf(stderr, "Missing GL function glUniform1f\n"); ok = false; }
    psgl_Uniform2f = reinterpret_cast<PFN_psglUniform2f>(getProc("glUniform2f"));
    if (!psgl_Uniform2f) { std::fprintf(stderr, "Missing GL function glUniform2f\n"); ok = false; }
    psgl_Uniform3f = reinterpret_cast<PFN_psglUniform3f>(getProc("glUniform3f"));
    if (!psgl_Uniform3f) { std::fprintf(stderr, "Missing GL function glUniform3f\n"); ok = false; }
    psgl_Uniform4f = reinterpret_cast<PFN_psglUniform4f>(getProc("glUniform4f"));
    if (!psgl_Uniform4f) { std::fprintf(stderr, "Missing GL function glUniform4f\n"); ok = false; }
    psgl_Uniform3fv = reinterpret_cast<PFN_psglUniform3fv>(getProc("glUniform3fv"));
    if (!psgl_Uniform3fv) { std::fprintf(stderr, "Missing GL function glUniform3fv\n"); ok = false; }
    psgl_Uniform4fv = reinterpret_cast<PFN_psglUniform4fv>(getProc("glUniform4fv"));
    if (!psgl_Uniform4fv) { std::fprintf(stderr, "Missing GL function glUniform4fv\n"); ok = false; }
    psgl_UniformMatrix4fv = reinterpret_cast<PFN_psglUniformMatrix4fv>(getProc("glUniformMatrix4fv"));
    if (!psgl_UniformMatrix4fv) { std::fprintf(stderr, "Missing GL function glUniformMatrix4fv\n"); ok = false; }
    psgl_GenTextures = reinterpret_cast<PFN_psglGenTextures>(getProc("glGenTextures"));
    if (!psgl_GenTextures) { std::fprintf(stderr, "Missing GL function glGenTextures\n"); ok = false; }
    psgl_BindTexture = reinterpret_cast<PFN_psglBindTexture>(getProc("glBindTexture"));
    if (!psgl_BindTexture) { std::fprintf(stderr, "Missing GL function glBindTexture\n"); ok = false; }
    psgl_TexImage2D = reinterpret_cast<PFN_psglTexImage2D>(getProc("glTexImage2D"));
    if (!psgl_TexImage2D) { std::fprintf(stderr, "Missing GL function glTexImage2D\n"); ok = false; }
    psgl_TexParameteri = reinterpret_cast<PFN_psglTexParameteri>(getProc("glTexParameteri"));
    if (!psgl_TexParameteri) { std::fprintf(stderr, "Missing GL function glTexParameteri\n"); ok = false; }
    psgl_TexParameterfv = reinterpret_cast<PFN_psglTexParameterfv>(getProc("glTexParameterfv"));
    if (!psgl_TexParameterfv) { std::fprintf(stderr, "Missing GL function glTexParameterfv\n"); ok = false; }
    psgl_ActiveTexture = reinterpret_cast<PFN_psglActiveTexture>(getProc("glActiveTexture"));
    if (!psgl_ActiveTexture) { std::fprintf(stderr, "Missing GL function glActiveTexture\n"); ok = false; }
    psgl_GenerateMipmap = reinterpret_cast<PFN_psglGenerateMipmap>(getProc("glGenerateMipmap"));
    if (!psgl_GenerateMipmap) { std::fprintf(stderr, "Missing GL function glGenerateMipmap\n"); ok = false; }
    psgl_DeleteTextures = reinterpret_cast<PFN_psglDeleteTextures>(getProc("glDeleteTextures"));
    if (!psgl_DeleteTextures) { std::fprintf(stderr, "Missing GL function glDeleteTextures\n"); ok = false; }
    psgl_GenFramebuffers = reinterpret_cast<PFN_psglGenFramebuffers>(getProc("glGenFramebuffers"));
    if (!psgl_GenFramebuffers) { std::fprintf(stderr, "Missing GL function glGenFramebuffers\n"); ok = false; }
    psgl_BindFramebuffer = reinterpret_cast<PFN_psglBindFramebuffer>(getProc("glBindFramebuffer"));
    if (!psgl_BindFramebuffer) { std::fprintf(stderr, "Missing GL function glBindFramebuffer\n"); ok = false; }
    psgl_FramebufferTexture2D = reinterpret_cast<PFN_psglFramebufferTexture2D>(getProc("glFramebufferTexture2D"));
    if (!psgl_FramebufferTexture2D) { std::fprintf(stderr, "Missing GL function glFramebufferTexture2D\n"); ok = false; }
    psgl_CheckFramebufferStatus = reinterpret_cast<PFN_psglCheckFramebufferStatus>(getProc("glCheckFramebufferStatus"));
    if (!psgl_CheckFramebufferStatus) { std::fprintf(stderr, "Missing GL function glCheckFramebufferStatus\n"); ok = false; }
    psgl_DeleteFramebuffers = reinterpret_cast<PFN_psglDeleteFramebuffers>(getProc("glDeleteFramebuffers"));
    if (!psgl_DeleteFramebuffers) { std::fprintf(stderr, "Missing GL function glDeleteFramebuffers\n"); ok = false; }
    psgl_DrawBuffer = reinterpret_cast<PFN_psglDrawBuffer>(getProc("glDrawBuffer"));
    if (!psgl_DrawBuffer) { std::fprintf(stderr, "Missing GL function glDrawBuffer\n"); ok = false; }
    psgl_ReadBuffer = reinterpret_cast<PFN_psglReadBuffer>(getProc("glReadBuffer"));
    if (!psgl_ReadBuffer) { std::fprintf(stderr, "Missing GL function glReadBuffer\n"); ok = false; }
    psgl_ReadPixels = reinterpret_cast<PFN_psglReadPixels>(getProc("glReadPixels"));
    if (!psgl_ReadPixels) { std::fprintf(stderr, "Missing GL function glReadPixels\n"); ok = false; }
    psgl_PixelStorei = reinterpret_cast<PFN_psglPixelStorei>(getProc("glPixelStorei"));
    if (!psgl_PixelStorei) { std::fprintf(stderr, "Missing GL function glPixelStorei\n"); ok = false; }
    psgl_GetString = reinterpret_cast<PFN_psglGetString>(getProc("glGetString"));
    if (!psgl_GetString) { std::fprintf(stderr, "Missing GL function glGetString\n"); ok = false; }
    psgl_GetError = reinterpret_cast<PFN_psglGetError>(getProc("glGetError"));
    if (!psgl_GetError) { std::fprintf(stderr, "Missing GL function glGetError\n"); ok = false; }
    return ok;
}
}  // namespace ps
