#pragma once
#include "rendering/ShaderLibrary.hpp"
#include "rendering/gl/Buffer.hpp"
#include "rendering/gl/Texture.hpp"
#include "rendering/gl/VertexArray.hpp"

#include <glm/glm.hpp>

#include <memory>
#include <string>
#include <vector>

namespace game::play {

/* THE HUD: flat coloured quads in pixels, and text set in a real typeface.
 *
 * The text used to be a 5x7 bitmap face, one quad per lit pixel, scaled up
 * -- which read as a retro pixel font at every size it was drawn ("the
 * text looks all pixelated, like a retro game"). Its first replacement,
 * DejaVu Sans Bold with a hard dark outline, was smooth but read as
 * cartoonish. It is now Barlow Condensed Medium -- a plain, condensed,
 * DIN-like face -- as a signed distance field (src/game/HudFont.inc,
 * generated by tools/make_hud_font.py and compiled in, so there is still
 * no font file to ship), with a soft offset shadow under it rather than an
 * outline: anti-aliased at every size, legible over sky and sand.
 *
 * Drawn into the renderer's output target after the frame, so a
 * screenshot carries it exactly as the window shows it. */
class Hud {
public:
    explicit Hud(rendering::ShaderLibrary& shaders);

    void begin(int width, int height);
    void rect(float x, float y, float w, float h, const glm::vec4& c);
    /* align: 0 left, 1 centre, 2 right. (x, y) is the top of the capitals.
       `px` keeps the old bitmap face's unit -- one of its seven rows -- so a
       call reads the same size it always did: capitals are 7 * px tall. */
    void text(const std::string& s, float x, float y, float px, const glm::vec4& c, int align = 0);
    [[nodiscard]] static float textWidth(const std::string& s, float px);
    void end(unsigned framebuffer);

    [[nodiscard]] int width() const { return m_w; }
    [[nodiscard]] int height() const { return m_h; }

private:
    struct V { glm::vec2 p; glm::vec2 uv; glm::vec4 c; float soft; };   // uv.x < 0: a flat quad; soft: a shadow
    void quad(glm::vec2 a, glm::vec2 b, glm::vec2 ua, glm::vec2 ub, const glm::vec4& c, float soft = 0.0f);
    std::shared_ptr<gl::Program> m_prog;
    rendering::ShaderLibrary& m_shaders;
    std::unique_ptr<gl::Buffer> m_vbo;
    gl::VertexArray m_vao;
    gl::Texture m_atlas;
    size_t m_cap = 0;
    std::vector<V> m_v;
    int m_w = 1, m_h = 1;
};

} // namespace game::play
