import json, re, math, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from shots_data import SHOTS

HERE = os.path.dirname(__file__)
LINES = {l['id']: l for l in json.load(open(os.path.join(HERE, 'lines.json')))}
OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
FPS = 24

# ------------------------------------------------------------ speech timing model
RATE_DEFAULT = 2.6      # words per second (~156 wpm), natural conversational delivery
RATE_NARRATOR = 2.2     # ~132 wpm, "clear, restrained, sparse"
RATE_SOFT = 1.8         # whispered / quietly / low / through pain
MIN_LINE = 0.6          # even a one-word line occupies at least this
SENTENCE_PAUSE = 0.25   # extra pause per internal sentence break
TURN_GAP = 0.35         # cue pickup / reaction gap per line


def line_seconds(l):
    note = l['note'].lower()
    if l['speaker'] == 'NARRATOR':
        rate = RATE_NARRATOR
    elif any(k in note for k in ('whisper', 'quietly', 'low', 'through pain')):
        rate = RATE_SOFT
    else:
        rate = RATE_DEFAULT
    breaks = len(re.findall(r'[.?!—](?=\s+\S)', l['text']))
    return round(max(MIN_LINE, l['words'] / rate) + breaks * SENTENCE_PAUSE + TURN_GAP, 2)


LINE_SOURCE = 'internal speech model (dialogue.json not found or not matching)'
DJ_TIMING_MODEL = None
for l in LINES.values():
    l['spoken_s'] = round(line_seconds(l) - TURN_GAP, 2)
    l['seconds'] = line_seconds(l)
_dj = os.path.join(OUT_DIR, 'dialogue.json')
if os.path.exists(_dj):
    _dl = {x['id']: x for x in json.load(open(_dj))['lines']}
    ok = len(_dl) == len(LINES) and all(
        i in _dl and _dl[i]['text'].strip()[:24] == LINES[i]['text'].strip()[:24] and isinstance(_dl[i].get('est_seconds'), (int, float))
        for i in LINES)
    if ok:
        DJ_TIMING_MODEL = json.load(open(_dj))['timing_model']
        for i, l in LINES.items():
            l['spoken_s'] = float(_dl[i]['est_seconds'])
            l['seconds'] = round(l['spoken_s'] + TURN_GAP, 2)
        LINE_SOURCE = 'dialogue.json est_seconds (ids and text verified identical) + %.2f s cue gap per line' % TURN_GAP
print('line timing source:', LINE_SOURCE)

# ------------------------------------------------------------ vocab
SIZE = {'EWS': 'extreme wide', 'WS': 'wide', 'MS': 'medium', 'CU': 'close', 'INS': 'insert', 'POV': 'POV', 'CARD': 'card (black/text, no 3D)'}

SETS = {
    'CARD_BLACK': 'Black frame or text on black. No 3D render: generated by the encoder (black) or a cheap 2D text page.',
    'SEA_COAST_DAWN': 'Prologue: open sea, rocky shore, island lost in cloud, small wooden sailing vessel, fog bank. Dawn.',
    'PROLOGUE_VISTAS': 'Prologue dissolves: coastal settlement, open sea, forest reaching a cliff, distant fortified walls, far unreached islands, wing-shaped cloud. Built from the same terrain/sea generators as the other sets. No map, no borders.',
    'BIRTHING_CHAMBER': 'Interior, Verdor: stone chamber, high daylight opening, lamps, prepared nest with bedding, bowls of water, folded cloth, the gold egg/hatchling. No magical apparatus.',
    'VERDOR_GROUNDS': 'Exterior, Verdor riding grounds: open grass field with a cleared launch area, Charcoal\'s grounded access rig, a low platform for Leaf, ground keepers, building doorway at the field edge. Also reused for the prologue\'s present-day shadow shot (meadow edge).',
    'SKY_OFF_VERDOR': 'Air: coast and island of Verdor on the inland side (screen LEFT in establishing shots), open sea on the other. Palace visible far off. Used for 1C (after take-off), 1D, 1E and Abby\'s intercuts in 1F.',
    'COASTAL_SKY_WATER': 'Air/sea: outer coast, a coastal outcrop, outer rocks, a low bank of sea mist, bright open water. Same ocean/terrain generator as SKY_OFF_VERDOR, different region. Used for 1F.',
    'TREATMENT_ROOM': 'Interior, Verdor: working room with daylight opening (coastline and outer rocks visible through it), seat, clean cloth, water; doorway to a corridor. 2B and 2C.',
    'VERDOR_HARBOR': 'Exterior, Verdor harbor: weathered steps down to the quay, the Santa Maria (name on hull only if legible), crew, ropes, supplies, a lookout. 2C insert.',
    'CLING_SQUARE': 'Exterior, Cling (within Scrapper): approach street, festival square with a fountain at the center (raised edge plus a central stone pillar: the continuous reference landmark, readable at foot level and above the dust), a separate substantial stone support by the king\'s steps (cover for the king and captain), vendor stall (left-center) with alley behind, music space (right-center), stone arch exit (screen LEFT from the steps), gate to broad road (screen RIGHT from the steps), banners, timber and gray stone. Must also exist in a damaged/dusty state for 3C-3D. Same layout as assets.json set.cling_village_square.',
    'CLING_SKY': 'Air above and around Cling: village small in its landscape, sky and cloud, Starlight and Queen Fall in flight, high views down onto the square.',
}

FLAG_TEXT = {
    'ABBY_BOTH_HANDS_BEFORE_PASS': 'Before the pass Abby uses both hands normally (set-up for the change).',
    'ABBY_LEFT_ARM_INJURY_EVENT': 'The pass wrenches Abby\'s LEFT arm. Do not mirror the shot.',
    'ABBY_LEFT_ARM_INJURED': 'Abby\'s LEFT arm is injured: held in, never used normally. Uses her right hand.',
    'ABBY_SLING_LEFT': 'Abby\'s LEFT arm is in a sling (from 2C onward).',
    'SCOUT_LEFT_WING_LOST': 'The scout lost its LEFT wing. Never show the right wing missing.',
    'SCOUT_SPECIES_SLITHERWING': 'The scout is a Slitherwing (small, very fast), not a Nightwing.',
    'SCOUT_RIDER_UNIDENTIFIED': 'Scout rider stays unidentified: no face, insignia, or speech.',
    'NO_WEAPON_STRIKE': 'The fracture comes from the pass and its wake, not from a weapon, bite, fall, or projectile.',
    'BURNED_RIDER_ALIVE': 'The burned rider is alive when last seen: strapped on, moving.',
    'NO_DEATH_DECLARED': 'Nobody declares the scout or its rider dead in Episode 1.',
    'STARLIGHT_NO_WOUNDS': 'Starlight has NO wounds (no later-episode wing injuries).',
    'STARLIGHT_NO_FIRE': 'Starlight never breathes fire in this episode. Damage comes only from the dive, contact, and her wake.',
    'STARLIGHT_SIZE': 'Starlight is roughly twice Charcoal\'s size. Reflective white scales; no glow, no literal crystal.',
    'ATTACK_NO_FLAME': '"Attack" means a physical attack. It never triggers flame.',
    'FIRE_ONLY_ON_FIRE_COMMAND': 'Charcoal\'s flame happens only after "Fire", and it is brief.',
    'CHARCOAL_NOT_FASTER': 'Charcoal is never faster than the Slitherwing in a straight line. He closes through angles and the scout\'s turns.',
    'LEAF_INITIATES_NIP': 'Leaf starts it with one quick, harmless nip.',
    'LEAF_UNHARMED': 'Leaf is unharmed by the head-in-mouth beat. Teeth never close through skin.',
    'SIZE_DISPARITY': 'Leaf is dramatically smaller than Charcoal (no exact ratio). Use long lenses so a foreground Leaf does not cheat the scale.',
    'HATCHLING_NO_GLOW': 'The gold hatchling reflects light but never emits it. It is weak and has no name.',
    'ORIGINAL_LINE_EXACT': 'An [ORIGINAL] line: use the exact wording.',
    'ABBY_SILENCE': 'Abby does not answer the succession question: no words, no nod, no narration.',
    'SCREEN_DIRECTION': 'Flight line: travel screen LEFT to RIGHT, camera on the inland side. Leaf LEFT/near and slightly behind, Charcoal RIGHT/far and ahead. Island on the inland side, open sea beyond them. Because they travel screen-right, this camera sees the dragons\' and riders\' RIGHT sides; their LEFT sides face seaward, away from camera.',
    'SPEAKING_DISTANCE': 'Airborne/field speakers are close enough to hear each other. Wind sits between the lines; no shouted conversations across impossible distances.',
    'REMI_CHECKS_ABBY_FIRST': 'Remi confirms Abby is secured and Leaf is stable before he pursues.',
    'FIELD_CLEAR': 'The launch field is cleared. No bystanders are endangered for spectacle.',
    'CLING_ROUTES': 'Cling map from the king\'s steps: stone arch LEFT, gate to broad road RIGHT, vendor stall left-center with alley behind, music space right-center, fountain with a central stone pillar at the center (the reference landmark), a separate stone support by the steps. Keep these fixed through the attack. Any reverse angle must be declared in camera_move and mirror these positions.',
    'TRAITOR_IS_SUSPICION_ONLY': 'Traitor is a suspicion, not a confirmed identity or motive.',
}

TAG_TEXT = {
    'CROWD': 'Many independently moving people (festival / evacuation).',
    'CROWD_SMALL': 'A handful of background people.',
    'FACE_CLOSEUP': 'Human face in close-up: expression must read, and faces must stay consistent between shots.',
    'LIPSYNC': 'On-camera speaking face: mouth shapes must match the recorded line.',
    'FIRE': 'Flame and burning cloth.',
    'SMOKE': 'Smoke trail.',
    'WATER_IMPACT': 'Splash, spray and a churned trail on the sea surface.',
    'OCEAN': 'Large animated sea surface.',
    'DUST': 'Volumetric dust / particulate clouds.',
    'DESTRUCTION': 'Breaking timber, tiles, turf, flying debris.',
    'HEAD_IN_MOUTH': 'Charcoal holds Leaf\'s whole head in his jaws mid-flight without harm.',
    'WING_SEPARATION': 'The scout\'s left wing tears loose (in silhouette, no gore).',
    'FAST_PASS': 'A tiny object crossing frame at extreme speed (motion blur, wake).',
    'HATCHLING_SOFTBODY': 'Wet, weak, soft-bodied newborn breaking out of a shell.',
    'GOLD_MATERIAL': 'Believable gold scales that reflect but do not glow.',
    'WHITE_SCALES': 'Reflective white scales that stay readable (not blown out, not glowing).',
    'BLACK_HIDE': 'Black scales that must keep texture and highlights (not a flat silhouette).',
    'SCALE': 'Showing enormous size convincingly.',
    'CLOTH': 'Cloth simulation (banners, clothing, torn fabric).',
    'GRASS': 'Grass reacting to wind.',
    'FOG': 'Volumetric fog / mist.',
    'HANDS_CONTACT': 'Hands touching or gripping objects or people.',
    'MOUNTING_RIG': 'Characters climbing onto or off dragons via rigs or platforms.',
    'BODY_MECHANICS': 'Believable human body weight and force.',
    'CREATURE_CONTACT': 'Two creatures in physical contact (bite, struggle).',
    'INSTRUMENT_ANIM': 'Playing a musical instrument.',
}
HARD_TAGS = {'CROWD', 'FACE_CLOSEUP', 'LIPSYNC', 'FIRE', 'WATER_IMPACT', 'DUST', 'HEAD_IN_MOUTH', 'WING_SEPARATION',
             'FAST_PASS', 'HATCHLING_SOFTBODY', 'DESTRUCTION', 'CREATURE_CONTACT'}
TAG_WEIGHT = {'HEAD_IN_MOUTH': 5, 'WING_SEPARATION': 5, 'FAST_PASS': 5, 'WATER_IMPACT': 5, 'FIRE': 5, 'DESTRUCTION': 5,
              'CROWD': 4, 'HATCHLING_SOFTBODY': 4, 'CREATURE_CONTACT': 5, 'DUST': 4, 'FACE_CLOSEUP': 3, 'LIPSYNC': 3,
              'MOUNTING_RIG': 3, 'BODY_MECHANICS': 3, 'CLOTH': 3, 'WHITE_SCALES': 3, 'BLACK_HIDE': 2, 'GOLD_MATERIAL': 2,
              'FOG': 3, 'SCALE': 2, 'OCEAN': 2, 'HANDS_CONTACT': 2, 'SMOKE': 3, 'GRASS': 2, 'CROWD_SMALL': 2, 'INSTRUMENT_ANIM': 3}

EDIT_PLAN = [  # screenplay editing-plan windows (minutes)
    ('PROLOGUE+TITLE', 'Historical prologue and main title', 0, 3),
    ('1A', 'The gold hatchling', 3, 7.5),
    ('1B', 'Preparing to fly', 7.5, 10.5),
    ('1C', 'Takeoff and open sky', 10.5, 14),
    ('1D', 'Siblings, succession, and the playful nip', 14, 18),
    ('1E', 'The first fast pass', 18, 20.5),
    ('1F', 'Pursuit and the scout\'s fall', 20.5, 25),
    ('2A', 'Return to Verdor', 25, 28),
    ('2B', 'Treatment and Remi\'s report', 28, 33),
    ('2C', 'Santa Maria orders and sibling aftermath', 33, 35.5),
    ('3A', 'Cling\'s festival and its king', 35.5, 39.5),
    ('3B', 'The white dragon approaches', 39.5, 42),
    ('3C', 'Starlight\'s attack', 42, 47),
    ('3D', 'Aftermath and cliffhanger', 47, 49),
    ('END', 'End credits', 49, 50),
]
SCENE_TITLE = {'PROLOGUE': 'Prologue: before the sky had riders', 'TITLE': 'Main title'}
SCENE_TITLE.update({c: t for c, t, *_ in EDIT_PLAN})


def rhalf(x):
    return math.floor(x * 2 + 0.5) / 2


def parse_inframe(s):
    out = []
    parts, depth, cur = [], 0, ''
    for ch in s:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(cur); cur = ''
        else:
            cur += ch
    parts.append(cur)
    for part in [p.strip() for p in parts if p.strip()]:
        # split on the LAST @ that is followed by a position token
        if '@' in part:
            name, pos = part.rsplit('@', 1)
        else:
            name, pos = part, ''
        out.append({'name': name.strip(), 'screen_pos': pos.strip()})
    return out


def speaker_in_frame(speaker, inframe):
    sp = speaker.lower()
    for f in inframe:
        n = f['name'].lower()
        if n.startswith(sp) or sp in n:
            return True
    return False


# ------------------------------------------------------------ expand
coverage = {}
shots = []
order_index = {s['sid']: i for i, s in enumerate(SHOTS)}
i_injury = order_index['1E-04']
i_sling = order_index['2C-12']
i_cling = order_index['3A-01']
i_burn = order_index['1F-14']
i_wing = order_index['1F-20']

for idx, s in enumerate(SHOTS):
    inframe = parse_inframe(s['inframe'])
    names = ' '.join(f['name'].lower() for f in inframe)
    dlg = []
    dlg_s = 0.0
    for tok in s['lines'].split():
        if ':' in tok:
            lid, portion = tok.split(':'); portion = float(portion)
        else:
            lid, portion = tok, 1.0
        assert re.fullmatch(r'L\d{3}', lid) and lid in LINES, (s['sid'], tok)
        L = LINES[lid]
        coverage[lid] = coverage.get(lid, 0) + portion
        assert L['scene'] == s['code'] or (s['code'] == 'PROLOGUE'), (s['sid'], lid, L['scene'])
        entry = {'id': lid, 'speaker': L['speaker'], 'first_words': ' '.join(L['text'].split()[:6]),
                 'spoken_s': L['spoken_s'], 'line_seconds': L['seconds']}
        if portion != 1.0:
            entry['portion'] = portion
        if L['note']:
            entry['delivery'] = L['note']
        on = L['speaker'] != 'NARRATOR' and L['speaker'] not in s.get('off', []) and speaker_in_frame(L['speaker'], inframe)
        entry['speaker_on_screen'] = on
        dlg.append(entry)
        dlg_s += L['seconds'] * portion
    assert isinstance(s['a'], (int, float)) and isinstance(s['b'], (int, float)), s['sid']
    a, b = float(s['a']), float(s['b'])

    tags = list(dict.fromkeys(s.get('tags', [])))
    if any(d['speaker_on_screen'] for d in dlg) and s['size'] in ('MS', 'CU'):
        tags.append('LIPSYNC')
    for t in tags:
        assert t in TAG_TEXT, (s['sid'], t)

    flags = list(s.get('flags', []))
    def addf(f):
        if f not in flags:
            flags.append(f)
    if idx > i_injury and idx < i_cling and 'abby' in names:
        addf('ABBY_LEFT_ARM_INJURED')
    if idx >= i_sling and idx < i_cling and 'abby' in names:
        addf('ABBY_SLING_LEFT')
    if 'starlight' in names:
        addf('STARLIGHT_NO_WOUNDS'); addf('STARLIGHT_NO_FIRE')
    if 'hatchling' in names:
        addf('HATCHLING_NO_GLOW')
    if 'charcoal' in names and 'leaf' in names:
        addf('SIZE_DISPARITY')
    if idx >= i_wing and 'scout' in names and 'rider' not in names.replace('scout rider', ''):
        pass
    if idx >= i_wing and re.search(r'\bscout\b(?! rider)', names):
        addf('SCOUT_LEFT_WING_LOST')
    if idx >= i_burn and 'scout rider' in names:
        addf('BURNED_RIDER_ALIVE')
    if s['code'] == '1F' and 'charcoal' in names and 'scout' in names:
        addf('CHARCOAL_NOT_FASTER')
    if any('ORIGINAL' in LINES[d['id']]['note'] for d in dlg):
        addf('ORIGINAL_LINE_EXACT')
    for f in flags:
        assert f in FLAG_TEXT, (s['sid'], f)

    # difficulty
    diff = s.get('diff')
    def tw_(t):
        if t == 'DUST' and s['code'] == '3D' and 'DESTRUCTION' not in tags:
            return 3  # settled haze, not an active dust simulation
        return TAG_WEIGHT.get(t, 2)
    auto = max([2 if inframe else 1] + [tw_(t) for t in tags])
    if diff is None:
        diff = auto
    diff = max(diff, 2 if inframe else 1)
    hard_tags = [t for t in tags if t in HARD_TAGS]
    hard = diff >= 4  # one rule everywhere: 'hard' means difficulty 4 or 5

    render = s.get('render', '3d')
    # twos
    tw = s.get('twos')
    if render != '3d':
        twos, twos_reason = 'n/a', 'No 3D render (black or text card).'
    else:
        fast_tags = [t for t in tags if t in ('DUST', 'DESTRUCTION', 'FIRE', 'WATER_IMPACT', 'FAST_PASS', 'CROWD', 'CLOTH', 'OCEAN', 'GRASS', 'SMOKE')]
        cam = s['cam'].lower()
        moving_cam = any(k in cam for k in ('air-to-air', 'follow', 'track', 'travel', 'pull-back', 'pan', 'tilt', 'shake', 'handheld', 'aerial', 'pov, flying', 'route'))
        if tw is None:
            tw = 'no' if (moving_cam or fast_tags) else 'ok'
        locked = cam.startswith('static') and not re.search(r'push|pan|drift|sway|follow|tilt', cam)
        busy = [t for t in tags if t in ('CROWD', 'DESTRUCTION', 'FIRE', 'WATER_IMPACT', 'FAST_PASS')]
        if 'DUST' in tags and s['code'] != '3D':
            busy.append('DUST')
        if tw == 'ok' and (not locked or busy):
            tw = 'no'
            if not locked:
                moving_cam = True
            fast_tags = sorted(set(fast_tags) | set(busy))
        if s.get('twos_why') and tw == 'no':
            twos, twos_reason = 'no', s['twos_why']
        elif tw == 'ok':
            twos = 'ok'
            twos_reason = 'Locked-off camera and slow character motion: holding each frame for two reads as a style choice, not a judder.' + (' Only slow settling dust haze, which reads fine on twos.' if 'DUST' in tags else '')
        else:
            twos = 'no'
            why = []
            if moving_cam:
                why.append('moving camera (air-to-air/tracking/pan/tilt) would visibly judder on twos')
            if fast_tags:
                why.append('fast secondary motion (' + ', '.join(t.lower() for t in fast_tags) + ') needs every frame')
            if not why:
                why.append('fast or large motion in frame needs every frame')
            twos_reason = '; '.join(why).capitalize() + '.'

    # render complexity (UNMEASURED planning guess)
    cx = 1.0
    if render != '3d':
        cx = 0.0
    else:
        if s['set'] in ('CLING_SQUARE', 'CLING_SKY'):
            cx += 0.2
        if s['set'] in ('SKY_OFF_VERDOR', 'COASTAL_SKY_WATER', 'SEA_COAST_DAWN', 'PROLOGUE_VISTAS'):
            cx += 0.15
        if 'CROWD' in tags:
            cx += 0.4
        if any(t in tags for t in ('DUST', 'DESTRUCTION', 'FIRE', 'WATER_IMPACT', 'FOG')):
            cx += 0.5
        if 'CLOTH' in tags:
            cx += 0.1
        cx = round(min(cx, 2.5), 2)

    est = rhalf(dlg_s + a + b)
    low = rhalf(0.9 * dlg_s + 0.8 * a + 0.5 * b)
    high = rhalf(1.15 * dlg_s + 1.3 * a + 1.5 * b)
    if s['sid'] == 'E-01':
        low, est, high = 30.0, 40.0, 60.0

    shot = {
        'id': s['sid'], 'scene': s['code'], 'set': s['set'],
        'time_of_day': s['tod'], 'lighting': s['light'],
        'shot_size': SIZE[s['size']], 'camera_move': s['cam'],
        'in_frame': inframe,
        'action': s['action'],
        'dialogue': dlg,
        'sound': s['sound'],
        'continuity_flags': flags,
        'timing': {'dialogue_s': round(dlg_s, 2), 'action_s': a, 'breath_s': b},
        'est_seconds': est, 'est_low_s': low, 'est_high_s': high,
        'frames_at_24fps': int(round(est * FPS)),
        'render': render,
        'twos': twos, 'twos_reason': twos_reason,
        'difficulty': diff, 'difficulty_tags': tags, 'hard': bool(hard),
        'render_complexity_guess': cx,
    }
    if s.get('note'):
        shot['note'] = s['note']
    shots.append(shot)

# ------------------------------------------------------------ checks
missing = [lid for lid in LINES if abs(coverage.get(lid, 0) - 1.0) > 1e-6]
assert not missing, ('line coverage problem', missing, {k: coverage.get(k) for k in missing})
ids = [s['id'] for s in shots]
assert len(ids) == len(set(ids)), 'duplicate shot ids'
# chronological dialogue order
seen = []
for s in shots:
    for d in s['dialogue']:
        n = int(d['id'][1:])
        if not seen or seen[-1] != n:
            assert not seen or n == seen[-1] + 1, ('order', s['id'], d['id'], seen[-1])
            seen.append(n)
assert seen == list(range(1, len(LINES) + 1))
# no Attack shot may contain fire tag
for s in shots:
    if any(d['id'] in ('L078', 'L180') for d in s['dialogue']):
        assert 'FIRE' not in s['difficulty_tags']
    if 'starlight' in ' '.join(f['name'].lower() for f in s['in_frame']):
        assert 'FIRE' not in s['difficulty_tags'], s['id']

# ------------------------------------------------------------ totals
def scene_group(code):
    return 'PROLOGUE+TITLE' if code in ('PROLOGUE', 'TITLE') else code

scene_rows = []
for code, title, m0, m1 in EDIT_PLAN:
    ss = [s for s in shots if scene_group(s['scene']) == code]
    exp = sum(s['est_seconds'] for s in ss)
    lo = sum(s['est_low_s'] for s in ss)
    hi = sum(s['est_high_s'] for s in ss)
    dl = sum(s['timing']['dialogue_s'] for s in ss)
    nlines = len({d['id'] for s in ss for d in s['dialogue']})
    scene_rows.append({
        'scene': code, 'title': title, 'shots': len(ss), 'spoken_lines': nlines,
        'dialogue_s': round(dl, 1),
        'low_s': lo, 'expected_s': exp, 'high_s': hi,
        'plan_window': f'{int(m0):02d}:{int(round((m0 % 1) * 60)):02d}-{int(m1):02d}:{int(round((m1 % 1) * 60)):02d}',
        'plan_s': round((m1 - m0) * 60),
        'expected_vs_plan_pct': round(100 * exp / ((m1 - m0) * 60)),
        'hard_shots': sum(1 for s in ss if s['hard']),
    })

T_exp = sum(r['expected_s'] for r in scene_rows)
T_lo = sum(r['low_s'] for r in scene_rows)
T_hi = sum(r['high_s'] for r in scene_rows)
T_dlg = sum(s['timing']['dialogue_s'] for s in shots)
T_act = sum(s['timing']['action_s'] for s in shots)
T_br = sum(s['timing']['breath_s'] for s in shots)

# ------------------------------------------------------------ render cost
def hrs(frames, fps):
    return round(frames / fps / 3600, 2)

f3d = [(s['est_seconds'] * FPS, s['twos'] == 'ok', s['render_complexity_guess']) for s in shots if s['render'] == '3d']
frames_total = int(round(T_exp * FPS))
frames_3d = int(round(sum(f for f, _, _ in f3d)))
frames_twos_ok = int(round(sum(f for f, ok, _ in f3d if ok)))
frames_rendered_with_twos = int(round(sum(f / 2 if ok else f for f, ok, _ in f3d)))
frames_3d_cx = sum(f * c for f, _, c in f3d)
frames_3d_cx_twos = sum((f / 2 if ok else f) * c for f, ok, c in f3d)

# Rendered frames per second, measured by render/bench.mjs (pipeline README, 'How fast is it?',
# updated 2026-10-05 01:12): test-kingdom scene, 3 browsers, x264 included, while a low-priority
# background job used up to 1.5 CPU threads. --twos does not change the rendered fps; it halves the
# number of frames that must be rendered.
NATIVE = (0.37, 0.42)   # final (native 3840x2160)
FAST = (0.48, 0.56)     # final-fast (2560x1440 upscaled to 4K): 0.56 on ones, 0.48 in the --twos run
PREVIEW = (1.44, 1.44)  # preview 1920x1080
DRAFT = (3.06, 3.35)    # draft 960x540: 3.06 in bench (4 browsers), 3.35 in the real 10 s clip

def rng(frames, fps_pair):
    return {'best_h': hrs(frames, fps_pair[1]), 'worst_h': hrs(frames, fps_pair[0])}

render_cost = {
    'basis': {
        'fps_output': FPS,
        'native_4k_rendered_fps_total': list(NATIVE),
        'final_fast_rendered_fps_total': list(FAST),
        'preview_1080p_rendered_fps_total': list(PREVIEW),
        'draft_540p_rendered_fps_total': list(DRAFT),
        'render_minutes_per_finished_minute_native_4k_all_ones': [round(24 / NATIVE[1], 1), round(24 / NATIVE[0], 1)],
        'source': 'MEASURED with render/bench.mjs on this 4-core CPU-only machine (SwiftShader, no GPU), scene scenes/test-kingdom.js (castle, ~13,700 instanced trees, lake, dragon, 4096 shadow map), 3 browsers in parallel, x264 included. Numbers from the pipeline README table updated 2026-10-05 01:12. A low-priority background job used up to 1.5 CPU threads during those measurements, so an idle machine may be the same or a bit faster. final-fast = render 2560x1440 and upscale to 3840x2160 in the shader (measured ~1.3-1.5x faster than native, not 2x). draft = 960x540 (measured 3.06 fps in bench with 4 browsers, 3.35 fps on a real 10 s clip). An earlier, lighter test measured ~0.9-1.15 fps at native 4K; this plan does not rely on that faster figure. Replace with per-set measurements once each set exists.',
        'black_and_text_cards': 'Not 3D-rendered (generated by the encoder or a cheap 2D page). Counted as 0 render hours.',
        'twos_mechanics': 'render.mjs --twos applies to a whole render job (frame o shows rendered frame o - o%2). To mix ones and twos, split render jobs at the shot boundaries listed in twos_segments, or add a per-shot twos switch to the scene timeline.',
    },
    'expected_runtime_s': T_exp,
    'frames_total_at_24fps': frames_total,
    'frames_3d': frames_3d,
    'frames_on_twos_eligible_shots': frames_twos_ok,
    'pct_3d_frames_twos_eligible': round(100 * frames_twos_ok / frames_3d, 1),
    'pct_runtime_twos_eligible': round(100 * frames_twos_ok / (T_exp * FPS), 1),
    'pct_note': 'pct_3d_frames_twos_eligible = share of the 3D-rendered frames; pct_runtime_twos_eligible = share of the whole expected runtime (cards and end titles included).',
    'frames_actually_rendered_with_twos': frames_rendered_with_twos,
    'scenarios_hours_one_pass': {
        'native_4k_all_on_ones': rng(frames_3d, NATIVE),
        'native_4k_twos_where_allowed': rng(frames_rendered_with_twos, NATIVE),
        'final_fast_all_on_ones': rng(frames_3d, FAST),
        'final_fast_twos_where_allowed': rng(frames_rendered_with_twos, FAST),
        'preview_1080p_all_on_ones': rng(frames_3d, PREVIEW),
        'draft_540p_animatic_all_on_ones': rng(frames_3d, DRAFT),
        'draft_540p_animatic_twos_where_allowed': rng(frames_rendered_with_twos, DRAFT),
        'final_fast_twos_where_allowed_plus_native_4k_for_hero_shots': 'see PRODUCTION_PLAN.md (mixed plan)',
    },
    'runtime_range_native_4k_all_ones': {
        'low_runtime': rng(sum(s['est_low_s'] * FPS for s in shots if s['render'] == '3d'), NATIVE),
        'high_runtime': rng(sum(s['est_high_s'] * FPS for s in shots if s['render'] == '3d'), NATIVE),
    },
    'complexity_adjusted_GUESS': {
        'warning': 'UNMEASURED. Per-shot multipliers (render_complexity_guess: 1.0 simple interior ... up to 2.5 crowd+dust) are planning guesses that heavy sets (crowds, dust, sea, Starlight + village) render slower than the benchmark scene. Replace with measured per-set seconds/frame once each set exists.',
        'weighted_frame_cost_vs_benchmark': round(frames_3d_cx / frames_3d, 2),
        'native_4k_all_on_ones': rng(frames_3d_cx, NATIVE),
        'native_4k_twos_where_allowed': rng(frames_3d_cx_twos, NATIVE),
        'final_fast_twos_where_allowed': rng(frames_3d_cx_twos, FAST),
    },
    'retakes_note': 'These are single-pass numbers. Real productions re-render: plan on ~2-3 draft passes per shot while blocking, and ~1.3-1.5x the final pass for fixes. The bottleneck is authoring ~%d shots of procedural animation, not render hours.' % len(shots),
}

# twos segments (contiguous runs) for the render jobs
segs = []
for s in shots:
    if s['render'] != '3d':
        mode = s['render']
    else:
        mode = 'twos' if s['twos'] == 'ok' else 'ones'
    if segs and segs[-1]['mode'] == mode and segs[-1]['scene'] == s['scene']:
        segs[-1]['to'] = s['id']; segs[-1]['seconds'] += s['est_seconds']
    else:
        segs.append({'scene': s['scene'], 'mode': mode, 'from': s['id'], 'to': s['id'], 'seconds': s['est_seconds']})
render_cost['twos_segments'] = segs

hardest = sorted([s for s in shots if s['hard']], key=lambda s: (-s['difficulty'], ids.index(s['id'])))

meta = {
    'title': "Dragon's Kingdom - S01E01 - shot list and runtime estimate (animatic plan)",
    'status': 'PLAN ONLY. Nothing has been rendered for this episode. These are estimated durations for an animatic, not measured footage.',
    'source': 'episodes/s01e01/screenplay.md (CANON LOCK, PRODUCTION CONTINUITY and FINAL CONTINUITY CHECK are binding)',
    'generated': '2026-10-05',
    'fps': FPS,
    'delivery_target': '3840x2160, 24 fps (screenplay suggests 1080p minimum; 4K is the decided production target)',
    'line_numbering': 'Dialogue ids L001..L198 count every spoken line (including NARRATOR) from the top of the SCREENPLAY section in order of appearance; each SPEAKER: block is one line (so "Hold—" and "Hold!" are two lines, and the king\'s interrupted speech is L169 / L171 with the vendor\'s "You are!" as L170). first_words is included so ids can be cross-checked against dialogue.json.',
    'speech_timing_model': {
        'used_for_this_build': LINE_SOURCE,
        'formula': 'line_seconds = dialogue.json est_seconds + turn_gap_s' if DJ_TIMING_MODEL else 'line_s = max(min_line, words / rate) + sentence_breaks * pause + turn_gap',
        'turn_gap_s': TURN_GAP,
        'dialogue_json_timing_model': DJ_TIMING_MODEL,
        'fallback_model_only_if_dialogue_json_is_missing': {
            'default_words_per_s': RATE_DEFAULT, 'narrator_words_per_s': RATE_NARRATOR, 'soft_words_per_s': RATE_SOFT,
            'min_line_s': MIN_LINE, 'internal_sentence_pause_s': SENTENCE_PAUSE,
            'note': 'NOT used for this build. The real rates are in dialogue_json_timing_model (2.6 w/s conversational, 2.1 w/s slow and narrator).'},
        'fields': 'dialogue[].spoken_s = speech only; dialogue[].line_seconds = speech + cue gap (what the shot timing uses)',
        'note': 'Replace with measured durations of the real recorded/temp voice lines once they exist; the shot timings then update by recomputing dialogue_s.',
    },
    'estimate_model': {
        'expected': 'dialogue_s + action_s + breath_s, rounded to 0.5 s',
        'low': '0.9*dialogue + 0.8*action + 0.5*breath (tight cutting)',
        'high': '1.15*dialogue + 1.3*action + 1.5*breath (slower performances, longer holds)',
        'end_titles': 'set by hand: 30 / 40 / 60 s, because the length depends on the real credits',
        'no_padding': 'No shot is lengthened to reach a target runtime. breath_s = the screenplay\'s explicit holds, silences and pauses (e.g. Abby\'s silence, holds on faces, the last prologue landscape) PLUS small performance breaths of 0.5-1 s on some ordinary exchanges. Where the screenplay asks for brevity (1D-26: \'keep it brief\') there is no breath. The real values come from the animatic.',
    },
    'shot_size_values': list(SIZE.values()),
    'render_values': {'3d': 'three.js scene render', 'black': 'black frame (encoder-generated)', 'text': 'text card (2D)'},
    'twos_values': {'ok': 'may be rendered on twos', 'no': 'must be on ones', 'n/a': 'not 3D-rendered'},
    'difficulty_scale': '1 = routine ... 5 = hardest to make convincing procedurally on CPU-only three.js',
    'hard_rule': 'hard = difficulty >= 4 (the same rule for every shot, for totals.hard_shots, scene_totals[].hard_shots and hardest_shots).',
}

conventions = {
    'flight_line_1C_to_1E': FLAG_TEXT['SCREEN_DIRECTION'] + ' In singles, Remi looks screen-LEFT toward Abby and Abby looks screen-RIGHT toward Remi.',
    'the_pass_1E': 'Travel stays screen LEFT to RIGHT with the camera on the inland side, so the camera sees Leaf\'s and Abby\'s RIGHT sides. The scout comes head-on from ahead (enters frame RIGHT), crosses R-to-L and cuts through the gap between Leaf and Charcoal: it passes along Leaf\'s LEFT (seaward) side, the FAR side from camera, never between Leaf and the camera. The wake hits Abby\'s LEFT side; her LEFT arm is the arm wrenched. Leaf rolls to his RIGHT (away from the wake, toward the inland side and the camera). The injury close-up 1E-04 is a declared neutral-axis shot from directly ahead of Leaf: Abby faces camera, so her LEFT arm is on screen RIGHT. 1E-05 returns to the inland side (her RIGHT hand grips in the foreground; the injured LEFT arm is held in on the far side). In 1F, Leaf heads inland = screen LEFT, so his and Abby\'s LEFT sides face camera again (1F-09). Do not mirror any of these shots.',
    'the_pass_1E_topdown': [
        'TOP-DOWN VIEW, 1E (travel = screen RIGHT for the inland camera)',
        '                         SEA (seaward)',
        '        CHARCOAL  ===>                     (ahead, far from camera)',
        '   - - - - gap - - - - - - <=== SCOUT      (comes head-on from ahead, passes through the gap)',
        '   LEAF + ABBY  ===>                       (behind, near camera; LEFT side faces the gap)',
        '                         ISLAND (inland)',
        '          [CAMERA, inland side, looking seaward]       [1E-04 camera: ahead of Leaf, looking back]',
    ],
    'pursuit_1F': 'Leaf heads inland (screen LEFT). The scout runs along the outer coast (screen RIGHT/far). Charcoal turns between them. For the wing-separation shot the camera is above and behind the scout, so its LEFT wing is screen LEFT against bright water.',
    'sun_verdor': 'Morning-to-day sun is over the sea side. On the inland-side camera axis the sea and sun are behind the action (rim light), so faces need fill light.',
    'verdor_grounds_map': 'Charcoal and his access rig on screen RIGHT (the large cleared launch area). Leaf and Abby across the field on screen LEFT, near the building doorway. The ground keeper stands at the far-left field edge.',
    'birthing_chamber_map': 'Nest in the center, Alexandria on screen RIGHT of the nest, attendant on LEFT, door at LEFT background. Abby crouches front-left.',
    'treatment_room_map': 'Camera faces seated Abby. Her LEFT arm (injured) is screen RIGHT, where the healer works. Alexandria kneels screen LEFT and holds Abby\'s RIGHT hand. Door and opening are on the LEFT background, and the coast is visible through the opening.',
    'cling_map': FLAG_TEXT['CLING_ROUTES'] + ' The sun is behind the steps (south). Starlight approaches from the far (north) sky. Pass 1 crosses north to south, striking the north-west festival structures and roofline. Pass 2 is a low sweep after she banks beyond the village.',
    'scale': 'Leaf is dramatically smaller than Charcoal (screenplay: about 1/20 Charcoal\'s size or smaller; no exact linear ratio). Starlight is roughly twice Charcoal\'s size. Keep the disparity readable in every shot that shows two of them.',
}

data = {
    'meta': meta,
    'sets': [{'id': k, 'description': v, 'shots': sum(1 for s in shots if s['set'] == k),
              'expected_s': sum(s['est_seconds'] for s in shots if s['set'] == k)} for k, v in SETS.items()],
    'conventions': conventions,
    'continuity_flag_definitions': FLAG_TEXT,
    'difficulty_tag_definitions': TAG_TEXT,
    'shots': shots,
    'scene_totals': scene_rows,
    'totals': {
        'shots': len(shots), 'spoken_lines': len(LINES), 'spoken_words': sum(l['words'] for l in LINES.values()),
        'dialogue_s': round(T_dlg, 1), 'spoken_speech_only_s': round(sum(l['spoken_s'] for l in LINES.values()), 1),
        'cue_gaps_s': round(T_dlg - sum(l['spoken_s'] for l in LINES.values()), 1),
        'action_s': round(T_act, 1), 'breath_s': round(T_br, 1),
        'low_s': T_lo, 'expected_s': T_exp, 'high_s': T_hi,
        'low_min': round(T_lo / 60, 1), 'expected_min': round(T_exp / 60, 1), 'high_min': round(T_hi / 60, 1),
        'screenplay_target_min': 50,
        'expected_vs_target_pct': round(100 * T_exp / 3000),
        'hard_shots': len(hardest), 'difficulty_5_shots': sum(1 for s in shots if s['difficulty'] == 5),
        'twos_eligible_shots': sum(1 for s in shots if s['twos'] == 'ok'),
        'shots_per_difficulty': {str(k): sum(1 for s in shots if s['difficulty'] == k) for k in range(1, 6)},
        'shots_per_tag': {t: sum(1 for s in shots if t in s['difficulty_tags']) for t in TAG_TEXT},
        'shots_per_size': {v: sum(1 for s in shots if s['shot_size'] == v) for v in SIZE.values()},
    },
    'render_cost': render_cost,
    'hardest_shots': [{'id': s['id'], 'difficulty': s['difficulty'], 'tags': [t for t in s['difficulty_tags'] if t in HARD_TAGS],
                       'what': s['action'][:140]} for s in hardest],
}
assert all(s['set'] in SETS for s in shots)

if os.environ.get('WRITE') == '1':
    json.dump(data, open(os.path.join(OUT_DIR, 'shotlist.json'), 'w'), indent=1, ensure_ascii=False)
json.dump(data, open(os.path.join(HERE, 'shotlist.snapshot.json'), 'w'), indent=1, ensure_ascii=False)

# ------------------------------------------------------------ console report
def mmss(x):
    x = int(round(x)); return f'{x // 60}:{x % 60:02d}'
print('shots', len(shots), 'lines', len(LINES))
for r in scene_rows:
    print(f"{r['scene']:15s} {r['shots']:3d} shots  lo {mmss(r['low_s']):>6} exp {mmss(r['expected_s']):>6} hi {mmss(r['high_s']):>6}  plan {r['plan_window']} ({mmss(r['plan_s'])}) {r['expected_vs_plan_pct']}%  hard {r['hard_shots']}")
print('TOTAL lo', mmss(T_lo), 'exp', mmss(T_exp), 'hi', mmss(T_hi), ' dialogue', mmss(T_dlg), 'action', mmss(T_act), 'breath', mmss(T_br))
print(json.dumps(render_cost['scenarios_hours_one_pass'], indent=0))
print(json.dumps(render_cost['complexity_adjusted_GUESS'], indent=0))
print('twos eligible %', render_cost['pct_runtime_twos_eligible'], 'frames_total', frames_total, 'frames_3d', frames_3d)
print('runtime range native', render_cost['runtime_range_native_4k_all_ones'])
print('hard shots', len(hardest), 'segments', len(segs))
