// Fast image-based lighting for the cinematic stack.
//
// three.js samples its PMREM environment ("textureCubeUV") twice per pixel of
// every PBR material - diffuse irradiance and glossy radiance - and on a CPU
// rasteriser that lookup is expensive (measured: ~1/3 of the ocean pass and
// ~1/2 of the main pass of HDRI-lit scenes). Once per environment change
// this module bakes:
//   * the diffuse irradiance as 9 spherical-harmonic coefficients (Ramamoorthi
//     & Hanrahan 2001) -> 9 multiply-adds per pixel, exact for a cosine lobe to ~1%
//   * a 1024x512 mip-mapped equirect of the sharp environment -> one
//     trilinear tap for glossy reflections, the mip chosen from the GGX lobe width
// The patched materials (materials.js, DK_FASTIBL) use these instead.
import * as THREE from 'three';
import { raw } from './passes.js';

function cubeUvDefines(env) {
  const h = env.image.height;
  const maxMip = Math.log2(h) - 2;
  return { CUBEUV_TEXEL_WIDTH: 1.0 / (3 * Math.max(Math.pow(2, maxMip), 7 * 16)), CUBEUV_TEXEL_HEIGHT: 1.0 / h, CUBEUV_MAX_MIP: maxMip.toFixed(1), ENVMAP_TYPE_CUBE_UV: 1 };
}

function makeBakeMaterial(defines) {
  return raw(/* glsl */ `
#define PI 3.141592653589793
#define RECIPROCAL_PI 0.3183098861837907
#define saturate(a) clamp(a, 0.0, 1.0)
#define texture2D texture
uniform sampler2D envMap;
uniform vec2 uSize;
uniform float uRough;
${THREE.ShaderChunk.cube_uv_reflection_fragment}
out vec4 o;
void main() {
  vec2 uv = gl_FragCoord.xy / uSize;
  float phi = (uv.x - 0.5) * 2.0 * PI, th = (uv.y - 0.5) * PI;
  vec3 d = vec3(cos(phi) * cos(th), sin(th), sin(phi) * cos(th));
  o = vec4(textureCubeUV(envMap, d, uRough).rgb, 1.0);
}`, { envMap: { value: null }, uSize: { value: new THREE.Vector2(1, 1) }, uRough: { value: 0 } }, defines);
}

export const FAST_IBL_GLSL = /* glsl */ `
uniform vec3 dkSH[9];              // irradiance SH (cosine lobe already applied), environment space
uniform sampler2D dkEnvEq;         // sharp environment, equirect, mip-mapped
uniform float dkEnvEqMaxLod;
vec3 dkSHIrr(vec3 n) {
  return max(vec3(0.0),
      dkSH[0] * 0.282095
    + dkSH[1] * (0.488603 * n.y) + dkSH[2] * (0.488603 * n.z) + dkSH[3] * (0.488603 * n.x)
    + dkSH[4] * (1.092548 * n.x * n.y) + dkSH[5] * (1.092548 * n.y * n.z) + dkSH[6] * (0.315392 * (3.0 * n.z * n.z - 1.0))
    + dkSH[7] * (1.092548 * n.x * n.z) + dkSH[8] * (0.546274 * (n.x * n.x - n.y * n.y)));
}
// radiance along an environment-space direction for a GGX roughness
vec3 dkEnvRadiance(vec3 r, float roughness) {
  vec3 shL = dkSHIrr(r) * 0.3183099;               // a lobe as wide as the cosine: irradiance / pi
  if (roughness > 0.62) return shL;
  vec2 uv = vec2(atan(r.z, r.x) * 0.15915494 + 0.5, asin(clamp(r.y, -1.0, 1.0)) * 0.3183099 + 0.5);
  float a = max(roughness * roughness, 0.004);      // GGX alpha ~ lobe width (rad)
  float lod = clamp(log2(a / 0.0061359), 0.0, dkEnvEqMaxLod);   // 0.0061 rad = one texel of the 1024-wide map
  vec3 c = textureLod(dkEnvEq, uv, lod).rgb;
  return mix(c, shL, smoothstep(0.4, 0.62, roughness));
}
`;

export class EnvBake {
  constructor(host) {
    this.h = host;
    this.key = null;
    this.sh = Array.from({ length: 9 }, () => new THREE.Vector3());
    this.eqRT = new THREE.WebGLRenderTarget(1024, 512, {
      type: THREE.FloatType, depthBuffer: false, stencilBuffer: false, generateMipmaps: true,
      minFilter: THREE.LinearMipmapLinearFilter, magFilter: THREE.LinearFilter,
      wrapS: THREE.RepeatWrapping, wrapT: THREE.ClampToEdgeWrapping,
    });
    this.smallRT = new THREE.WebGLRenderTarget(64, 32, { type: THREE.FloatType, depthBuffer: false, stencilBuffer: false, generateMipmaps: false });
    this.maxLod = Math.log2(1024);
  }

  /** Re-bake when scene.environment changed. Returns true while an environment is active. */
  update(scene) {
    const env = scene.environment;
    if (!env || env.mapping !== THREE.CubeUVReflectionMapping || !env.image?.height) { this.active = false; return false; }
    const key = `${env.uuid}:${env.version}:${env.image.height}`;
    if (key === this.key) { this.active = true; return true; }
    const defs = cubeUvDefines(env);
    const dk = JSON.stringify(defs);
    if (dk !== this.defKey) {
      this.pass?.material.dispose();
      this.pass = this.h.makePass(makeBakeMaterial(defs));
      this.defKey = dk;
    }
    const u = this.pass.material.uniforms;
    u.envMap.value = env;
    // sharp equirect (+ mips, generated by three after the draw)
    u.uSize.value.set(1024, 512); u.uRough.value = 0;
    this.h.drawPass(this.pass, this.eqRT);
    // small, slightly prefiltered copy -> CPU -> spherical harmonics
    u.uSize.value.set(64, 32); u.uRough.value = 0.35;
    this.h.drawPass(this.pass, this.smallRT);
    const px = new Float32Array(64 * 32 * 4);
    this.h.renderer.readRenderTargetPixels(this.smallRT, 0, 0, 64, 32, px);
    const c = Array.from({ length: 9 }, () => [0, 0, 0]);
    for (let y = 0; y < 32; y++) {
      const th = ((y + 0.5) / 32 - 0.5) * Math.PI, ct = Math.cos(th), st = Math.sin(th);
      const dw = ((2 * Math.PI) / 64) * (Math.PI / 32) * ct;
      for (let x = 0; x < 64; x++) {
        const ph = ((x + 0.5) / 64 - 0.5) * 2 * Math.PI;
        const dx = Math.cos(ph) * ct, dy = st, dz = Math.sin(ph) * ct;
        const Y = [0.282095, 0.488603 * dy, 0.488603 * dz, 0.488603 * dx, 1.092548 * dx * dy, 1.092548 * dy * dz, 0.315392 * (3 * dz * dz - 1), 1.092548 * dx * dz, 0.546274 * (dx * dx - dy * dy)];
        const i = 4 * (y * 64 + x);
        for (let k = 0; k < 9; k++) for (let ch = 0; ch < 3; ch++) c[k][ch] += px[i + ch] * Y[k] * dw;
      }
    }
    // irradiance = convolution with the clamped cosine: bands scaled by pi, 2pi/3, pi/4
    const A = [Math.PI, 2.094395, 2.094395, 2.094395, 0.785398, 0.785398, 0.785398, 0.785398, 0.785398];
    for (let k = 0; k < 9; k++) this.sh[k].set(c[k][0] * A[k], c[k][1] * A[k], c[k][2] * A[k]);
    this.key = key;
    this.active = true;
    return true;
  }

  bind(u) {
    u.dkSH.value = this.sh;
    u.dkEnvEq.value = this.eqRT.texture;
    u.dkEnvEqMaxLod.value = this.maxLod;
  }
}
