#!/usr/bin/env node
/* Extract the head and neck of the MakeHuman base mesh (hm08) and a set of
   its morph targets into an engine module (engine/src/94e-mh-head-data.js).

   The MakeHuman base mesh and targets were released as CC0 in September
   2020 (see the header of every file). Fetch them from
     https://raw.githubusercontent.com/makehumancommunity/makehuman/master/makehuman/data/3dobjs/base.obj
     https://raw.githubusercontent.com/makehumancommunity/makehuman/master/makehuman/data/targets/<dir>/<name>.target
   into one folder (targets as <dir>_<name>.target) and run:
     node tools/mh/extract_head.js <folder> engine/src/94e-mh-head-data.js

   Output, all little-endian base64:
     V  Float32 xyz of the kept vertices, MakeHuman units (decimetres)
     Q  Uint16 faces, 4 indices each (a triangle repeats its last index)
     EL/ER  local indices of the eye joint markers (their centre is the eyeball's)
     T  { name: [Uint16 local index..., Int16 dx,dy,dz x 1/5000 unit ...] } */
const fs = require('fs');
const path = require('path');
const [dir, out] = process.argv.slice(2);
const obj = fs.readFileSync(path.join(dir, 'base.obj'), 'utf8').split('\n');
const P = [];
const groups = {};
let g = null;
for (const l of obj) {
  if (l.startsWith('v ')) { const a = l.split(/\s+/); P.push([+a[1], +a[2], +a[3]]); }
  else if (l.startsWith('g ')) { g = l.slice(2).trim(); groups[g] = groups[g] || []; }
  else if (l.startsWith('f ') && g) groups[g].push(l.split(/\s+/).slice(1).filter(Boolean).map((s) => parseInt(s, 10) - 1));
}
const centre = (name) => { const s = new Set(groups[name].flat()); const c = [0, 0, 0]; for (const i of s) for (let k = 0; k < 3; k++) c[k] += P[i][k] / s.size; return { c, idx: [...s] }; };
const eL = centre('joint-l-eye'), eR = centre('joint-r-eye'), neck = centre('joint-neck'), head = centre('joint-head');
const ipd = Math.abs(eL.c[0] - eR.c[0]);
const toM = 0.0636 / ipd;                        // metres per MakeHuman unit, at a 6.36 cm interpupillary distance
// Keep the body down to 16.5 cm below the eyes (the old field head's stub reached the same depth).
const eyeY = (eL.c[1] + eR.c[1]) / 2;
const cutY = eyeY - 0.150 / toM;          // above the trapezius all round; 94f extends the neck from here into the collar
/* Below the jaw only the neck itself: a cylinder 9.5 cm in radius (94f caps it back to a neck) about the neck joint. Without
   it the cut took in the tops of the shoulders. */
const jawY = eyeY - 0.140 / toM;          // below the chin (12 cm under the eyes on an adult)
const inNeck = (i) => P[i][1] > jawY || Math.hypot(P[i][0] - neck.c[0], P[i][2] - neck.c[2]) < 0.095 / toM;
const faces = groups.body.filter((f) => f.every((i) => P[i][1] > cutY));
void inNeck;
const used = new Map();
const local = (i) => { if (!used.has(i)) used.set(i, used.size); return used.get(i); };
const Q = [];
for (const f of faces) { const q = f.map(local); while (q.length < 4) q.push(q[q.length - 1]); Q.push(...q.slice(0, 4)); }
const EL = eL.idx.map(local), ER = eR.idx.map(local);
const V = new Float32Array(used.size * 3);
for (const [gi, li] of used) for (let k = 0; k < 3; k++) V[li * 3 + k] = P[gi][k];
const T = {};
let entries = 0;
/* Not kept: the 'old' ancestry targets (head-age-incr covers age on a head) and the universal
   macro targets (the base mesh already is the universal young average), and head-scale-* (plain
   stretches, done in code). */
for (const f of fs.readdirSync(dir).filter((n) => n.endsWith('.target') && !/-old\.|universal-|head-scale-/.test(n)).sort()) {
  const idx = [], d = [];
  const mirror = /(^|_)l-/.test(f) || /(^|_)r-/.test(f);
  for (const l of fs.readFileSync(path.join(dir, f), 'utf8').split('\n')) {
    if (!l || l[0] === '#') continue;
    const a = l.trim().split(/\s+/); const gi = +a[0];
    if (!used.has(gi)) continue;
    const q = [+a[1], +a[2], +a[3]].map((v) => Math.max(-32767, Math.min(32767, Math.round(v * 5000))));
    // Under 0.15 mm on a real head (1.5e-3 units) is below anything the mesh can show.
    if (Math.max(Math.abs(q[0]), Math.abs(q[1]), Math.abs(q[2])) < 8) continue;
    idx.push(used.get(gi)); d.push(...q);
  }
  if (!idx.length) continue;
  const name = f.replace(/\.target$/, '').replace(/^[a-z]+_/, '');
  const buf = Buffer.concat([Buffer.from(new Uint16Array(idx).buffer), Buffer.from(new Int16Array(d).buffer)]);
  T[name] = [idx.length, buf.toString('base64')];
  entries += idx.length;
  void mirror;
}
const b64 = (ta) => Buffer.from(ta.buffer).toString('base64');
const src = `/* ─────────── generated by tools/mh/extract_head.js -- do not edit ───────────
   The head and neck of the MakeHuman base mesh (hm08) and ${Object.keys(T).length} of its morph
   targets. Both were released by the MakeHuman team as CC0 (public domain) in
   September 2020: "This asset was explicitly released as CC0 in september 2020."
   ${used.size} vertices, ${Q.length / 4} faces, ${entries} target entries. */
const MH_HEAD = {
  toM: ${toM.toFixed(6)},
  eyeY: ${eyeY.toFixed(5)},
  V: '${b64(V)}',
  Q: '${b64(new Uint16Array(Q))}',
  EL: ${JSON.stringify(EL)}, ER: ${JSON.stringify(ER)},
  T: ${JSON.stringify(T)},
};
`;
fs.writeFileSync(out, src);
console.log(`${used.size} verts, ${Q.length / 4} faces, ${Object.keys(T).length} targets, ${entries} entries, ${(src.length / 1024).toFixed(0)} KB; toM ${toM.toFixed(5)}; neck ${neck.c.map((v) => v.toFixed(2))} head ${head.c.map((v) => v.toFixed(2))} eyes ${eL.c.map((v) => v.toFixed(3))}`);
