#!/usr/bin/env bash
# Regenerates ALL-IN-ONE.md by concatenating every design doc in reading order.
# Run from the repo root:  bash game/design/build-combined.sh
set -euo pipefail
cd "$(dirname "$0")"   # game/design

OUT="ALL-IN-ONE.md"

# Reading order: bible first, then missions in order, then world/systems.
FILES=(
  GAME_DESIGN.md
  missions/mission-01.md
  missions/mission-02.md
  missions/mission-03.md
  missions/mission-04.md
  missions/mission-05.md
  missions/mission-06.md
  missions/mission-07.md
  missions/mission-08-molotov-flashback.md
  missions/mission-09.md
  missions/mission-10.md
  missions/mission-11.md
  missions/mission-12.md
  missions/mission-13.md
  modes/new-mode-post-epilogue.md
  factions.md
  arsenal.md
  hydra-drone-h1.md
  emp-shark.md
  roster-tracker.md
  dlc-sins-of-the-past.md
)

{
  echo "# UNTITLED GAME — COMBINED DESIGN DOC (ALL-IN-ONE)"
  echo
  echo "> **AUTO-GENERATED SNAPSHOT.** Do NOT edit this file directly — edit the"
  echo "> individual files under \`game/design/\` and regenerate with"
  echo "> \`bash game/design/build-combined.sh\`. The organized files are the source"
  echo "> of truth; this is a concatenated copy for easy reading/export."
  echo
  echo "Contents (in order):"
  for f in "${FILES[@]}"; do echo "- \`$f\`"; done
  echo
  for f in "${FILES[@]}"; do
    echo
    echo "═══════════════════════════════════════════════════════════════════════"
    echo "# ▓▓▓ FILE: $f ▓▓▓"
    echo "═══════════════════════════════════════════════════════════════════════"
    echo
    cat "$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
